FROM mysql:latest

RUN chown -R mysql:root /var/lib/mysql/

ENV MYSQL_DATABASE=babyteacher
ENV MYSQL_USER=babyuser
ENV MYSQL_PASSWORD=pass
ENV MYSQL_ROOT_PASSWORD=pass

ADD setup.sql /etc/mysql/setup.sql

RUN sed -i 's/MYSQL_DATABASE/'$MYSQL_DATABASE'/g' /etc/mysql/setup.sql
RUN cp /etc/mysql/setup.sql /docker-entrypoint-initdb.d

EXPOSE 3306
