FROM mongo:latest

# Définir les variables d'environnement pour l'utilisateur MongoDB
ENV MONGO_INITDB_ROOT_USERNAME=babyUser
ENV MONGO_INITDB_ROOT_PASSWORD=toto

# Copier le script d'initialisation de la base de données
COPY ./init-mongo.js /docker-entrypoint-initdb.d/

# Exposer le port par défaut de MongoDB
EXPOSE 27017