name: 'Deployment'

on:
  push:
    branches:
      - main

jobs:
  build-backend-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get commit hash
        run: echo "COMMIT_HASH=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV
      - name: Docker login to registry
        run: echo "${{ secrets.REGISTRY_PASS }}" | docker login rg.fr-par.scw.cloud/babyteacher-regitstry -u nologin --password-stdin
      - name: Build the Docker image for the backend
        run: docker build . -f Dockerfile_back --tag rg.fr-par.scw.cloud/babyteacher-registry/backend:latest
      - name: Push the image to private registry
        run: docker push rg.fr-par.scw.cloud/babyteacher-registry/backend

  build-mongo-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get commit hash
        run: echo "COMMIT_HASH=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV
      - name: Docker login to registry
        run: echo "${{ secrets.REGISTRY_PASS }}" | docker login rg.fr-par.scw.cloud/babyteacher-regitstry -u nologin --password-stdin
      - name: Build the Docker image for the mongodb
        run: docker build --build-arg MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }} --build-arg MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }} . -f Dockerfile_mongo --tag rg.fr-par.scw.cloud/babyteacher-registry/mongo:latest
      - name: Push the image to private registry
        run: docker push rg.fr-par.scw.cloud/babyteacher-registry/mongo

  build-database-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get commit hash
        run: echo "COMMIT_HASH=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV
      - name: Docker login to registry
        run: echo "${{ secrets.REGISTRY_PASS }}" | docker login rg.fr-par.scw.cloud/babyteacher-regitstry -u nologin --password-stdin
      - name: Build the Docker image for the mysql database
        run: docker build --build-arg MYSQL_USER=${{ secrets.MYSQL_USER }} --build-arg MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} --build-arg MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} . -f Dockerfile_mysql --tag rg.fr-par.scw.cloud/babyteacher-registry/mysql:latest
      - name: Push the image to private registry
        run: docker push rg.fr-par.scw.cloud/babyteacher-registry/mysql

  trigger_workflow:
    runs-on: ubuntu-latest
    needs:
      - build-backend-image
      - build-mongo-image
      - build-database-image
    steps:
      - name: Trigger terraform workflow
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with: 
          owner: SurfingOwl
          repo: iac_terraform
          github_token: ${{ secrets.ACTIONS_KEY }}
          workflow_file_name: terraform_deploy.yml
          ref: main
          wait_interval: 30
          propagate_failure: true
          wait_workflow: true
