name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image for the backend
        run: docker build . --file Dockerfile_back --tag myRegistry.com/babyteacher-back:$(date +%s) && docker push myRegistry.com/babyteacher-back
